# Basic operator configuration for Rook v1.17.8
image:
  tag: v1.17.8
  repository: docker.io/rook/ceph
  pullPolicy: IfNotPresent

crds:
  enabled: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

unreachableNodeTolerationSeconds: 5

monitoring:
  enabled: true

csi:
  enableRbdDriver: true
  enableCSIHostNetwork: true
  enableCephfsDriver: true
  enableNFSDriver: false # This key is for the legacy NFS provisioner, not the CSI driver
  disableCsiDriver: "false"
  # - enableCephfsSnapshotter
  # - enableNFSSnapshotter
  # - enableRBDSnapshotter
  enablePluginSelinuxHostMount: false
  enableCSIEncryption: true
  pluginPriorityClassName: system-node-critical
  provisionerPriorityClassName: system-cluster-critical

  rbdFSGroupPolicy: "File"
  cephFSFSGroupPolicy: "File"
  enableOMAPGenerator: false
  enableMetadata: false
  provisionerReplicas: 2
  logLevel: 0
  grpcTimeoutInSeconds: 150

  csiRBDProvisionerResource:
    - name: csi-provisioner
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-resizer
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-attacher
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-snapshotter
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-rbdplugin
      resource:
        requests:
          memory: "512Mi"
        limits:
          memory: "1Gi"
    - name: csi-omap-generator
      resource:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
    - name: liveness-prometheus
      resource:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"

  csiRBDPluginResource:
    - name: driver-registrar
      resource:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
    - name: csi-rbdplugin
      resource:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
    - name: liveness-prometheus
      resource:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"

  csiCephFSProvisionerResource:
    - name: csi-provisioner
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-resizer
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-attacher
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-snapshotter
      resource:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
    - name: csi-cephfsplugin
      resource:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
    - name: liveness-prometheus
      resource:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"

  csiCephFSPluginResource:
    - name: driver-registrar
      resource:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
    - name: csi-cephfsplugin
      resource:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
    - name: liveness-prometheus
      resource:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"

  # NOTE: The image tags below are for a newer CSI version.
  # The defaults for Rook v1.17.8 are older (e.g., cephcsi:v3.11.0).
  # You may need to adjust these if you encounter compatibility issues.
  cephcsi:
    repository: quay.io/cephcsi/cephcsi
    tag: v3.15.0
  registrar:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.13.0
  provisioner:
    repository: registry.k8s.io/sig-storage/csi-provisioner
    tag: v5.2.0
  snapshotter:
    repository: registry.k8s.io/sig-storage/csi-snapshotter
    tag: v8.2.1
  attacher:
    repository: registry.k8s.io/sig-storage/csi-attacher
    tag: v4.8.1
  resizer:
    repository: registry.k8s.io/sig-storage/csi-resizer
    tag: v1.13.2

  imagePullPolicy: IfNotPresent
  provisionerTolerations: []
  pluginTolerations: []
  enableLiveness: false
  forceCephFSKernelClient: true
  serviceMonitor:
    enabled: false
  topology:
    enabled: false
  cephFSAttachRequired: true
  rbdAttachRequired: true

  nfs:
    enabled: false

pspEnable: false

currentNamespaceOnly: false
operatorPodLabels: {}
annotations: {}
logLevel: INFO
rbacEnable: true

rbacAggregate:
  # The key 'enableOBCs' was corrected to 'obc' for v1.17.8
  obc: false

priorityClassName: ""

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 2016
  runAsGroup: 2016
  capabilities:
    drop: ["ALL"]

allowLoopDevices: false


enableDiscoveryDaemon: false
discoveryDaemonInterval: 60m
cephCommandsTimeoutSeconds: "15"
scaleDownOperator: false

discover:
  toleration: ""
  tolerationKey: ""
  tolerations: []
  nodeAffinity: ""
  podLabels: {}
  resources: {}

hostpathRequiresPrivileged: false
enforceHostNetwork: true
disableDeviceHotplug: false
imagePullSecrets: []
enableOBCWatchOperatorNamespace: true
obcProvisionerNamePrefix: ""
obcAllowAdditionalConfigFields: "maxObjects,maxSize"
